TaskManager/urls.py
from unicodedata import name
from django import views
from django.contrib import admin
from django.urls import path, include
from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_page, name = "homepage" ),
    path('dashboard/', include('dashboard.urls')),
    path('projects/', include('projects.urls')),
    path('user/', include('Team.urls')),
]

Team/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.Team,  name="user-page"),
    path('registration/', views.registration, name = "registration"),
    path('login/', views.login_page, name = "login"),
    path('logout/', views.logout_user, name = "logout"),
    path('my-profile/', views.show_profile, name = "my-profile"),
    path('search-user/', views.search_user, name = 'search-user'),
]

projects/urls.py
from django.conf import settings
from django.conf.urls.static import static
from unicodedata import name
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name = "home"),

    #all projects (personal + group)
    path('projects/', views.project_view, name = "projects" ),
    path('projects/ <str:pk>/', views.team_projects, name = "team_projects" ),
    path('projects/start-task/', views.start_task, name = 'start-task'),

    #personal projects link
    path('show-projects/', views.default_personalProject, name = 'show-pp' ),
    path('show-projects/<str:pk>', views.show_personal_projects, name = 'view-pp' ),
    path('personal-project/', views.create_personalProject, name = "create-pp"),
    path('group-project/', views.create_group_project, name = "add-group-project"),
    path('delete-pp/<str:pk>', views.delete_personalProject, name = "delete-pp"),
    path('delete-pt/<str:pk>', views.delete_personalTask, name = "delete-pt"),
    path('delete-grouptask/<str:pk>', views.delete_group_task, name = "delete-grouptask"),
    path('update-grouptask/<str:pk>', views.update_group_task, name = 'update-grouptask'),
    path('personal-task/<str:pk>', views.create_personalTask, name = "create-pt"),
    path('group-task/<str:pk>', views.create_group_task, name = "create-gt"),
    path('update-pt/<str:pk>', views.update_personalTask, name = "update-personalTask"),
    path('mark-task/<str:pk>/', views.mark_completed_personaltask, name = "mark-completed"),
    path('mark-grouptask/<str:pk>/', views.mark_completed_grouptask, name = "mark-completed-gt"),
    path('search-projects/', views.search_projects, name = 'search-project'),

    #task-links
    path('task/<str:pk>/', views.show_task_detail, name = "task_detail"),
    path('update-task/<str:pk>/', views.update_task, name = "update_task"),
    path('delete-task/<str:pk>/', views.update_task, name = "delete_task"),
    path('create-task/', views.create_task, name = 'create-task'),

    #another links
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projects/models.py
from email import message
from django.utils import timezone
import datetime
from email.policy import default
from enum import unique
from pyexpat import model
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
# Create your models here.

#Create Base class
class BaseModel(models.Model):
    project_name = models.CharField(max_length=20)
    project_description = models.TextField(max_length=100)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    count = models.IntegerField(null=False, default=0)

    class Meta:
        abstract = True

#Personal Projects Model
class PersonalProjects(BaseModel):

    class Meta:
        ordering = ['created', 'updated']
    def __str__(self):
        return self.project_name

#create group project
class GroupProject(BaseModel, models.Model):
    members = models.ManyToManyField(User, blank = True,  through='GroupMembers', related_name="members")
    deadline_date = models.DateTimeField()

    def get_member_count(self, pk):
        return GroupProject.objects.filter(id=pk).count()

    def __str__(self):
        return self.project_name

class GroupMembers(models.Model):
    project= models.ForeignKey(GroupProject, on_delete=models.CASCADE)
    member = models.ForeignKey(User, on_delete=models.DO_NOTHING)

    def __str__(self):
        return str(self.member)

#Task Base Model
class Task(models.Model):
    task_name = models.CharField(max_length=50)
    description = models.TextField()
    deadline_date = models.DateTimeField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    is_completed = models.BooleanField()

    class Meta:
        abstract = True

#personal task models
class PersonalTask(Task, models.Model):
    project = models.ForeignKey(PersonalProjects, on_delete=models.CASCADE)
    user_name = models.ForeignKey(User, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):

        if self.deadline_date < timezone.now():
            raise ValidationError (f'Deadline date cannot be before {{timezone.now()}}' )
        super(PersonalTask, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.task_name

#Group Task
class GroupTask(Task, models.Model):
    project = models.ForeignKey(GroupProject, on_delete=models.CASCADE)
    assignedTo = models.ManyToManyField(GroupMembers, through="TaskAssignedTo")

    def save(self, *args, **kwargs):
    
        if self.deadline_date < timezone.now():
            raise ValidationError (f'Deadline date cannot be before {{timezone.now()}}' )
        super(GroupTask, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.task_name

class TaskAssignedTo(models.Model):
    user = models.ForeignKey(GroupMembers, on_delete=models.DO_NOTHING)
    task= models.ForeignKey(GroupTask, on_delete=models.CASCADE)

projects/forms.py
from dataclasses import field, fields
from pyexpat import model
from django.forms import ModelForm
from .models import GroupProject, GroupTask, PersonalTask, Task, PersonalProjects

#personal Project Form
class PersonalProjectForm(ModelForm):

    class Meta:

        model = PersonalProjects
        fields = [
            'project_name',
            'project_description',
        ]

#Group Project Form
class GroupProjectForm(ModelForm):

    class Meta:

        model = GroupProject
        fields = [
            'project_name',
            'project_description',
            'deadline_date',
        ]

#personal Task Form
class PersonalTaskForm(ModelForm):
    class Meta:

        model =  PersonalTask
        fields = [
            'task_name', 
            'description',
            'deadline_date',
        ]

#Group task form
class GroupTaskForm(ModelForm):
    class Meta:

        model = GroupTask
        fields = [

            'task_name', 
            'description',
            'deadline_date',
            'assignedTo',
        ]
class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = '__all__'

projects/views.py
from collections import UserDict
from multiprocessing import context
from operator import index
from pyexpat import model
from urllib import request
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from .models import GroupProject, GroupTask, PersonalTask, PersonalProjects
from .forms import GroupProjectForm, GroupTaskForm, TaskForm, PersonalProjectForm, PersonalTaskForm

@login_required(login_url='login')
def home(request):
    """Returns a homepage with user group project on it"""

    user  = User.objects.get(username = request.user)
    user_team = GroupProject.objects.filter(members = user.id)
    return render(request, 'dashboard/index.html', {'teams':user_team})
    
@login_required(login_url='login')
def project_view(request):
    """Returns a list of user tasks"""
    task_name = PersonalTask.objects.all().only('task_name')

    list_tasks = {}
    for task in task_name:
        list_tasks[f'{task}'] = PersonalTask.objects.filter(id=task.id)
    
    return render(request, 'projects/project_home.html', {'contrib':list_tasks})

class DefaultProject:

    def __init__(self, task_model, project_model, pk, user_id) -> None:
        filter_project = Q(created_by = user_id)
        self.filter_one = Q(project = pk)
        self.filter_two = Q(is_completed = False)
        self.filter_three = Q(is_completed = True)

        self.pending = task_model.objects.filter(self.filter_one & self.filter_two)
        self.completed = task_model.objects.filter(self.filter_one & self.filter_three)
        self.project = project_model.objects.get(id=pk)
        self.context = {}
    
    #get all projects
    def get_all_projects(self):
        return self.project.objects.filter(self.filter_project)
    #get project
    def get_project(self):
        return self.project
    
    #get pending task
    def get_pending_task(self):
        return self.pending
    
    #get completed task
    def get_completed_task(self):
        return self.completed

    #get count of pending task
    def get_count_pending(self):
        return self.completed
    
    #get count of completed task
    def get_count_completed(self):
        return self.completed.count()
    
    # get count of pending task
    def get_count_pending(self):
        return self.pending.count()
    
    # get context
    def get_context(self, project_type:str):

        self.context['pending'] = self.get_pending_task
        self.context['completed'] = self.get_completed_task
        self.context['count_pending'] = self.get_count_pending
        self.context['count_completed'] = self.get_count_completed
        self.context[f'{project_type}_default'] = self.get_project
        self.context['projects'] = self.get_all_projects

        return self.context

def get_default_context(pk, model_object, default_ctx):

        filter_one = Q(project = pk)
        filter_two = Q(is_completed = False)
        filter_three = Q(is_completed = True)

        pending = model_object.objects.filter(filter_one & filter_two)
        completed = model_object.objects.filter(filter_one & filter_three)
        
        context = {
            
            'pending': pending, 
            'count_pending':pending.count(),

            'completed':completed,
            'count_completed':completed.count(),
            'default':default_ctx.objects.get(id=pk),
        }

        return context

#show personal projects homepage
@login_required(login_url='login')
def show_personal_projects(request, pk):
    project = PersonalProjects.objects.get(id=pk)

    if request.user == project.created_by:
        personal_project = DefaultProject(PersonalTask, PersonalProjects, pk, request.user.id)
        context  = personal_project.get_context('personal')
        if request.method =="POST":
            if 'project_name' in request.POST:
                create_personalProject(request, request.user)
            elif 'task_name' in request.POST:
                create_personalTask(request, pk)
        else:
            pass
    else:
        messages.error(request, 'Requested anauthorized page')
    return render(request, 'projects/project_page.html', context)

#show all personal projects
@login_required(login_url='login')
def default_personalProject(request):
    All_projects  = PersonalProjects.objects.filter(created_by = request.user.id)

    context = {}
    if All_projects:
        personal_project = DefaultProject(PersonalTask, PersonalProjects, All_projects[0].id,request.user.id)
        context = personal_project.get_context('personal')

    return render(request, 'projects/project_page.html', context)


@login_required(login_url='login')
def create_personalProject(request):
    """Used to create a Personal project and store it in a database"""
    user_id  = request.user
    form = PersonalProjectForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        #associating the current user with database table(PersonalProjects)
        obj = form.save(commit = False)
        obj.created_by = user_id
        obj.save()

        form = PersonalProjectForm()
        messages.success(request, "Successfully created")
        return  redirect('projects')
    else:
        # do something here
        pass
    return render(request, 'projects/pp_form.html')

def create_group_project(request):
    """Used to create a group project and store it in database"""
    user_id  = request.user
    form = GroupProjectForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        #associating the current user with database table(PersonalProjects)
        obj = form.save(commit = False)
        obj.created_by = user_id
        obj.save()
        form = GroupProjectForm()
        messages.success(request, "Successfully created")
        return  redirect('projects')
    else:
        # do something here
        pass
    return render(request, 'dashboard/index.html')

@login_required(login_url='login')
def create_personalTask(request, pk):
    """Store a personal task and associate it with it's respective project"""
    form = PersonalTaskForm(request.POST or None, request.FILES or None)
    project = PersonalProjects.objects.get(id=pk)

    if form.is_valid():
        #associating the current user with database table(PersonalProjects)
        obj = form.save(commit = False)
        obj.user_name = request.user
        obj.is_completed = False
        obj.project = project
        obj.save()
        form = PersonalTaskForm()

        # update tasks under specific project
        project.count = PersonalTask.objects.filter(project=project).count()
        project.save()
        messages.success(request, "Successfully created")
        return  redirect('projects')
    else:
        #do something here
        pass
    return render(request, 'projects/pt_form.html')

@login_required(login_url='login')
def create_group_task(request, pk):
    """Store a group task and associate it with it's respective project"""
    requested_project = GroupProject.objects.get(id  = pk)

    if requested_project.created_by == request.user:
        form  = GroupTaskForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.project = requested_project
            obj.is_completed = False
            obj.save()

            colloborators = list(map(int, request.POST.getlist('assignedTo')))
            obj = GroupTask.objects.get(id = obj.id)
            obj.assignedTo.set(id for id in colloborators)
            obj.save()
                            
            form = GroupTaskForm()
            requested_project.count = GroupTask.objects.filter(project = requested_project).count()
            requested_project.save()

            messages.add_message(request, messages.INFO, f"{obj} task is added")
        else:
            #do something here
            pass
    else:
        messages.add_message(request, messages.INFO, "YOu are not authorized to create a task")
    return render(request, 'dashboard/index.html', get_default_context(pk, GroupTask, GroupProject))

#delete personal Project
def delete_personalProject(request, pk):
    project  = PersonalProjects.objects.get(id = pk)

    if request.method == 'POST':

        # project_tasks = PersonalTask.objects.filter(project=project)
        project.delete()
    
    return render(request, 'projects/project_page.html', {'obj':project})

#generic function/deleting task
def delete_task(request, task_model_name, project_model_name,  pk):
    task = task_model_name.objects.get(id = pk)
    project  = project_model_name.objects.get( id = task.project_id)

    if request.method == "POST":
        task.delete()

        #reducing number of counts
        project.count -=1
        project.save()
        return True
    return False

#delete personal Task
@login_required(login_url='login')
def delete_personalTask(request, pk):
    delete_task(request, PersonalTask, PersonalProjects, pk)
    return render(request, 'projects/project_page.html')

def delete_group_task(request, pk):
    delete_task(request, GroupTask, GroupProject, pk)
    return render(request, 'dashboard/index.html')

#search project functionality 
@login_required(login_url='login')

def search_projects(request):

    query = request.GET.get('query') if request.GET.get('query') is not None else ''
    try:
        context = {}
        project = PersonalProjects.objects.get(Q(project_name__icontains = query))
        if project.created_by == request.user:
            personal_project  = DefaultProject(PersonalTask, PersonalProjects, project.id, request.user.id)
            context = personal_project.get_context('personal')
        return render(request, 'projects/project_page.html', context)

    except Exception as e:

projects/templates/projects/Task_info.html
{% extends 'index.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'CSS/task_info.css' %}">
{% endblock %}

{% block content %}

<div class="task-detail">
    <div class="task_name">
        <h1>{{task.task_name}}</h1>
    </div>

    <div class="task-desciption">
        <p>{{task.description}}</p>
    </div>

    <div class="contributors">
        {% for name in task.assigned_to.all %}
            Assigned To: {{name}}
        {% endfor %}
    </div>

    <div class="task-detail-footer">
        <div class="edit-delete">
            <a href={% url 'update_task' task.id %}>Edit</a>
            <a href={% url 'delete_task' task.id %}>delete</a>
        </div>
    </div>
</div>
{% endblock %}

projects/templates/projects/delete.html
<form action="" method="post">
    {% csrf_token %}
    <p>Are you sure want to delte "{{obj.project_name}}"?</p>
    <input type="submit" value="Confirm">
</form>
<a href={% url 'delete-pp' project.id %}><i class='bx bx-message-square-x'></i></a>

<a href="#deleteProject{{project.id}}" class="btn btn-outline-primary" data-toggle="modal"
data-target="#deleteProject{{project.id}}"><i class='bx bx-message-square-x'></i></a>

<div class="modal fade" id="deleteProject{{project.id}}" tabindex="-1" role="dialog"
aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
<div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
        <form action="" method="post">
            {% csrf_token %}
            <p>Are you sure want to delte "{{obj.project_name}}"?</p>
            <input type="submit" value="Confirm">
        </form>
    </div>
    <div class="modal-footer">
        <input type="submit" class="btn btn-warning" value="Delete">
    </div>
</div>
</div>

projects/templates/projects/hello.html
<form action="" method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_task_name">Task name:</label>
        <input class="form-control" id="id_task_name" maxlength="50" name="task_name" required="" type="text" />
    </div>
    <div class="form-group">
        <label for="id_description">Description:</label>
        <textarea cols="40" id="id_description" name="description" required="" rows="10">
</textarea>
    </div>
    <div class="form-group">
        <label for="id_deadline_date">Deadline date:</label>
        <input class="form-control" id="id_deadline_date" name="deadline_date" required="" type="text" />
    </div>
    <div class="form-group">
        <label for="id_task_status">Task status:</label>
        <select id="id_task_status" name="task_status">
            <option selected="" value="TD">Todo Task</option>
            <option value="C">Completed Task</option>
            <option value="P">Inprogress Task</option>
        </select>
    </div>
    <input class="form-control" type="submit" value="submit" />
</form>

projects/templates/projects/project_home.html
{% extends 'index.html' %}
{% load static %}

{% block extra_head %}
    <link rel="stylesheet" href="{% static 'CSS/project.css' %}">
    <style>
        .project-section {
    padding: 20px;
}
.project-tasks {
    display: flex;
    justify-content: space-between;
}
.project-tasks .task {
    border: 1px salmon solid;
    width: 30%;
    padding: 10px;
}

.top {
    display: flex;
    flex-direction: row;
    justify-content: space-between;
}

a {
    text-decoration: none;
}
.btn {
    border: none;
    height: 25px;
    margin-top: 25px;
    font-size: 1.2rem;
    
}
.information {
    margin: 10px;
    border: 1px skyblue solid;
    border-radius: 10px;
    padding: 10px;
}
.topic-head, .task-footer {
    display: flex;
    justify-content: space-between;
}
    </style>
{% endblock %}

{% block content %}

    <div class="project-section">
        <span>hello, {{request.user}}</span>
        <div class="section-title">
            <h1>Projects</h1>
<a href="">Create Projects</a>

        </div>
    
        <div class="project-tasks">
            <div class="to_do task">
                <div class="top">
                    <h2>To-Do</h2>

                    <button class="btn"><a href={% url 'create-task' %}>Add Task</a></button>
                </div>
                <span>Total:{{no_todo}}</span>

                <!-- replace with real data from database -->
                <form action="" method=POST>
                    {% csrf_token %}
                    {% for task in todoTasks %}
                    <div class="information">
                        <div class="topic-head">
                            <a href={% url 'task_detail' task.task_name%}><span class="name">{{task.task_name}}</span></a>
                            <div>
                                <label for="mark"></label>
                                <input type="checkbox" name="mark"  class="checkbox" id="checkbox" value= {{task.id}} name="boxes">
                            </div>
                        </div>

                         <div class="content-taks">
                            <p>{{task.description}}</p>
                        </div> 
                        <div class="task-footer">
                            <!-- YOu should think about this feature -->
                            <div class="person-contrib" id="contrib">
                            </div>

                            <div class="edit-delete">
                                <a href="">Edit</a>
                                <a href="">Delete</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <button class="btn" value="submit" >Start Task</button>
                </form>

            </div>
            <div class="in_progress task">
                <h2>In-Progress</h2>
                <span>Total:{{no_inprogress}}</span>

                {% for task in inprogress %}
                <div class="information">
                    <div class="topic-head">
                        <span class="name">{{task.task_name}}</span>
                        <div>
                            <label for="completed">completed</label>
                            <input type="checkbox" name="completed">
                        </div>
                    </div>

                    <div class="content-taks">
                        <p>{{task.description}}</p>
                    </div>

                    <div class="task-footer">
                        <div class="person-contrib">
                            {{task.host.username}}
                        </div>
                    </div>
                </div>
            {% endfor %}

            </div>
            <div class="completed task">
                <h2>Completed</h2>
                <span>Total:{{no_completed}}</span>

                {% for task in completed %}
                <div class="information">
                    <div class="topic-head">
                        <span class="name">{{task.task_name}}</span>
                    </div>

                    <div class="content-taks">
                        <p>{{task.description}}</p>
                    </div>

                    <div class="task-footer">
                        <div class="person-contrib">
                            {{task.host.username}}
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}
{% block extraScript %}
<script>
    
function get_contrib(task){
    console.log("hello")
    console.log(task)
}
</script>
<!-- <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script> -->
<script src="{% static 'js/mark_task.js' %}"></script>
{% endblock %}

projects/templates/projects/pt_form.html
{% extends 'index.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'CSS/style.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<style>
    .form-section {
    width: 80%;
    margin: 0 auto;
    margin-top: 30px;
    padding: 10px;
    border: 1px solid lightblue;
}
</style>
{% endblock %}
{% block content %}
{{project_list}}, "hello"
<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="submit">
</form>
{% endblock %}
{% block extraScript %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
{% endblock %}

projects/templates/projects/task_form.html
{% extends 'index.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'CSS/style.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<style>
    .form-section {
    width: 80%;
    margin: 0 auto;
    margin-top: 30px;
    padding: 10px;
    border: 1px solid lightblue;
}
</style>
{% endblock %}
{% block content %}

<div class="form-section">
    <form action="" method="post">
        {% csrf_token %}        
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="id_task_name">Task name:</label>
            <input class = "form-control" id="id_task_name" maxlength="50" name="task_name" required="" type="text" />
          </div>
          <div class="form-group col-md-6">
            <label for="id_task_status">Task status:</label>
            <select class="form-control" id="id_task_status" name="task_status">
                <option selected="" value="TD">Todo Task</option>
                <option value="C">Completed Task</option>
                <option value="P">Inprogress Task</option>
            </select>
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="id_start_date">Start date:</label>
            <input class="form-control" id="id_start_date" name="start_date" required="" type="text" />
          </div>
          <div class="form-group col-md-6">
            <label for="id_deadline_date">Deadline date:</label>
            <input class="form-control" id="id_deadline_date" name="deadline_date" required="" type="text" />
          </div>
        </div>
    
        <div class="form-group">
            <label for="id_assigned_to">Assigned to:</label>
            <select class="form-control" id="id_assigned_to" multiple="" name="assigned_to" required="">
                <option value="1">ibsa</option>
                <option value="2">kena</option>
                <option value="3">jima_dube</option>
            </select>
        </div>
        <div class="form-group">
            <label for="id_description">Description:</label>
            <textarea class="form-control" cols="40" id="id_description" name="description" required="" rows="5">
        </textarea>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
</div>
{% endblock %}

{% block extraScript %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
{% endblock %}